/*
* Copyright LABGeM (2014)
*
* author: Jonathan MERCIER
*
* This software is a computer program whose purpose is to annotate a complete genome.
*
* This software is governed by the CeCILL license under French law and
* abiding by the rules of distribution of free software. You can use,
* modify and/ or redistribute the software under the terms of the CeCILL
* license as circulated by CEA, CNRS and INRIA at the following URL
* "http://www.cecill.info".
*
* As a counterpart to the access to the source code and rights to copy,
* modify and redistribute granted by the license, users are provided only
* with a limited warranty and the software's author, the holder of the
* economic rights, and the successive licensors have only limited
* liability.
*
* In this respect, the user's attention is drawn to the risks associated
* with loading, using, modifying and/or developing or reproducing the
* software by the user in light of its specific status of free software,
* that may mean that it is complicated to manipulate, and that also
* therefore means that it is reserved for developers and experienced
* professionals having in-depth computer Concept. Users are therefore
* encouraged to load and test the software's suitability as regards their
* requirements in conditions enabling the security of their systems and/or
* data to be ensured and, more generally, to use and operate it in the
* same conditions as regards security.
*
* The fact that you are presently reading this means that you have had
* Concept of the CeCILL license and that you accept its terms.
*/

package fr.cea.ig.grools;

import fr.cea.ig.grools.model.Knowledge;
import fr.cea.ig.grools.model.KnowledgeStatistics;
import fr.cea.ig.grools.model.LogicStatistics;
import fr.cea.ig.grools.model.FiveState;
import fr.cea.ig.grools.model.Conclusion;
global ch.qos.logback.classic.Logger logger;

dialect "mvel"

rule "insert KnowledgeStatistics"
    when
        $k:    Knowledge( presence != FiveState.UNEVALUATED, conclusion != Conclusion.UNEVALUATED )
        not(
                exists( Knowledge( this memberOf $k.partOf) )
            )
        not(
                exists( LogicStatistics( $k := knowledge ) )
            )
    then
        insert( new KnowledgeStatistics( $k ) );
end

rule "compute completeness"
    when
         $k:    Knowledge( presence != FiveState.UNEVALUATED )
         $ls:   LogicStatistics( $k := knowledge  )
         not( Float() from $ls.completeness )
         allSubKnowledgeHaveAConclusion( $k, $childs; )
         $counter: Number() from accumulate( $child: Knowledge( presence == FiveState.TRUE ) from $childs, count( $child ) )
    then
        if( $k.presence == FiveState.TRUE ){
            $counter++;
        }
        modify( $ls ){
            completeness = $counter * 100 / ($childs.size() + 1);
        }
end


rule "compute consistency"
    when
         $k:    Knowledge( presence != FiveState.UNEVALUATED )
         $ls:   LogicStatistics( $k := knowledge )
         not( Float() from $ls.consistency )
         allSubKnowledgeHaveAConclusion( $k, $childs; )
         $counter: Number() from accumulate( $child : Knowledge( conclusion (
                                                                                == Conclusion.CONFIRMED_PRESENCE    ||
                                                                                == Conclusion.CONFIRMED_ABSENCE     ||
                                                                                == Conclusion.UNCONFIRMED_PRESENCE  ||
                                                                                == Conclusion.UNCONFIRMED_ABSENCE
                                                                               )
                                                               ) from $childs, count( $child ) )
    then
        if( $k.conclusion == Conclusion.CONFIRMED_PRESENCE      ||
            $k.conclusion == Conclusion.CONFIRMED_ABSENCE       ||
            $k.conclusion == Conclusion.UNCONFIRMED_PRESENCE    ||
            $k.conclusion == Conclusion.UNCONFIRMED_ABSENCE ) {
             $counter++;
        }

        modify( $ls ){
            consistency = $counter * 100 / ($childs.size() +1 );
        }
end
